### ISSUE TITLE
Publish 1.0.0 release candidate

### ISSUE THREAD

**Issue by jw3** [apache/daffodil-vscode#78] opened 2022-02-10 13:16 UTC
Publish official 1.0.0-RC that can be tested and (eventually) promoted to the 1.0.0 final.

**Comment by jw3** [comment] 2022-02-10 13:17
@stevedlawrence @mbeckerle what needs to happen to get an RC published?

**Comment by stevedlawrence** [comment] 2022-02-10 13:48
Below is a summary of what must be done for the release process.

Although this is the minimum, I would suggest that you create a wiki page and release candidate container, similar to what we do with Daffodil, so that the process can be fully documented and automated to avoid potential errors. It also gives us a chance to review the release process. It might even be worth modifying the release candidate container to support choosing to build the extension or daffodil--much of the process will be very similar.

https://cwiki.apache.org/confluence/display/DAFFODIL/Release+Workflow

Here's the summary:

1. A [DISCUSS] email thread should be started to determine if a release should be started. That should be open for 72 hours.
 
1. Assuming the community agrees, a release manager is decided to perform the actions. Technically this person does not need to be a committer, but it makes the process much easier if they have committer privileges, so I recommend that.

1. That files that will be voted on must be created. A source zip and/or tar archive are mandatory. Convenience binaries (i.e. the .vsix file) are optional, but I recommend that we do those as well.

1. All release files must be signed with the release managers gpg key (see the release workflow for the gpg key creation process) and sha512sum hashes created.

1. All files and signatures/hashes must be uploaded to https://dist.apache.org/repos/dist/dev/daffodil/
 
1. A webpage on daffodil.apache.org should be created for to describe this release, including links to downloads, signature, hashes, etc.

5. The git repo should be tagged with a rc version number

6. A VOTE email must be sent out, and be open for at least 72 hours.

5. The vote passes if it receives at least 3 binding +1's, and more +1's than -1's

6. The release is moved from the dist.a.o/dev directory to dist.a.o/release/

7. A git tag is created

8. An announce email is sent out

**Comment by stevedlawrence** [comment] 2022-02-10 13:52
One issue right now is where files need to live on the dist server. Right now files go in

`https://dist.apache.org/repos/dist/release/daffodil/<version>`

We may need an additional subdirectory to differentiate between daffodil and the extension, and potentially other things in the future, for example:

`https://dist.apache.org/repos/dist/release/daffodil/daffodil/<version>`
`https://dist.apache.org/repos/dist/release/daffodil/daffodil-vscode/<version>`

Which involves moving our existing files. We can easily upate links on our webpage, but if anything outside that directly references the old links things may break. I suspect that's not too likely though.

It also involves updating the release candidate container, but if we modify the container to do both release, that seems like a pretty straightforward change.

**Comment by stevedlawrence** [comment] 2022-02-10 14:26
Another thought about reusing the Daffodil container--it current uses Java 8, which is not supported by this extension right now (Issue #16). Though, we might just consider fixing that. Replacing `Path.of` should be trivial, and I can't find any reference to the "nested object" issue mentioned in that bug and I can't reproduce any failures by creating nested objects in the scala REPL. Maybe that restriction has be removed in newer versions of scala?

**Comment by stevedlawrence** [comment] 2022-02-11 20:55
I've opened PR apache/daffodil#751 to add support for the daffodil release candidate container to work for vscode. This handles steps 3,4,5 and 7 mentioned above. There's still alot of other steps that require manual effort, but they are all pretty well documented in the release workflow, with some minor tweaks needed for vscode.

**Comment by jw3** [comment] 2022-02-15 14:38
> .. I can't find any reference to the "nested object" issue mentioned in that bug

Here was the original thread, there is a reference and stack trace to the nested object issue
https://github.com/jw3/example-daffodil-vscode/issues/94

> Maybe that restriction has be removed in newer versions of scala?

The scala bug looks to have been closed as a wont-fix based on the last comment.

I was able to reproduce our bug just now by running #79 on java 8.

**Comment by stevedlawrence** [comment] 2022-02-15 19:10
Thanks for the reference. If I'm reading the bug correctly, it sounds like this is only a runtime issue with Java 8 and not a compile time issue. And that we should still be able to compile things on Java 8, as long as it only runs on Java 9+. I ran a real simple test and that seems to be the case. I can build some nested objects and all `getSimpleName` on Java 8. If I run on Java 8 it fails, if I run on Java 11 it works (I don't have Java 9 to test).

So with PR#79 merged, it should mean that we can build the convenience binaries using the daffodil-release-candidate (which builds with Java 8) without having to change anything.

So essentially build requirements are Java 8+, run requirements are Java 9+? Does that seem reasonable?

**Comment by Shanedell** [comment] 2022-05-02 23:43
Release candidate 1.0.0 has been fully released so this closes this issues. https://daffodil.apache.org/vscode/

**Closed by Shanedell** 2022-05-02 23:43 UTC
