### ISSUE TITLE
Debug level INFO doesn't reduce the debug output

### ISSUE THREAD

**Issue by hdalsania** [apache/daffodil-vscode#843] opened 2023-09-12 16:07 UTC
In the launch.json, changing the debug level to INFO didn't reduce the huge debug output to the terminal.

Source of this ticket is approval VOTE [email](https://lists.apache.org/thread/0gcddqd3mhys5179t8zgkpp51l9oc6nv) from @mbeckerle  for v1.3.1-rc1 on 08/29/2023

**Comment by arosien** [comment] 2023-09-13 23:10
I couldn't reproduce this. Checking @mbeckerle's launch.json configuration...

**Comment by arosien** [comment] 2023-09-13 23:16
Using the
```json
      "dfdlDebugger": {
        "logging": { "file": "/tmp/daffodil-debugger.log", "level": "INFO" }
      } 
```
I see only INFO level logging, and changing it to DEBUG shows DEBUG logging also.

Closing as cannot reproduce.

**Closed by arosien** 2023-09-13 23:16 UTC
Labels: debugger, configuration
